{{- if (include "rustfs.modeStandalone?" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rustfs.fullname" . }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  {{- with .Values.mode.standalone.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rustfs.selectorLabels" . | nindent 6 }}
  template:
    {{- include "rustfs.podTemplate" . | nindent 4}}
{{- end }}
