{{- if (include "rustfs.modeDistributed?" .) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rustfs.fullname" . }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "rustfs.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "rustfs.selectorLabels" . | nindent 6 }}
  template:
    {{- include "rustfs.podTemplate" . | nindent  4 }}
  volumeClaimTemplates:
    {{- with .Values.persistence.logs }}
    - metadata:
        name: logs
        labels:
          {{- toYaml .Values.commonLabels | nindent 8 }}
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .storageClass -}}
        {{- if eq .storageClass "-" }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .storageClass }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ required ".persistence.logs.size is required" .size }}
    {{- end }}
    {{- range $i, $vol :=  .Values.persistence.data }}
    - metadata:
        name: data-rustfs-disk-{{ $i }}
        labels:
          {{- toYaml $.Values.commonLabels | nindent 10 }}
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if $vol.storageClass -}}
        {{- if eq $vol.storageClass "-" }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ $vol.storageClass }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ required (printf ".persistence.data[%d].size is required" $i) $vol.size }}
    {{- end }}
{{- end }}
